import json

def create_notebook():
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": ["# Inizializzazione e Caricamento Dati\n", "In questa sezione importiamo le librerie necessarie e carichiamo il dataset del MAGIC Gamma Telescope. Il dataset contiene 10 features continue e 1 label (h=hadron, g=gamma)."]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "import os\n",
            "import math\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import re\n\n",
            "from sklearn.model_selection import train_test_split\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, recall_score, f1_score, roc_curve, roc_auc_score\n",
            "from sklearn.ensemble import RandomForestClassifier\n",
            "from sklearn.svm import SVC\n",
            "from sklearn.cluster import KMeans\n",
            "from sklearn.decomposition import PCA\n",
            "from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score, silhouette_score\n",
            "from sklearn.utils.class_weight import compute_class_weight\n\n",
            "import tensorflow as tf\n",
            "from tensorflow.keras.models import Sequential\n",
            "from tensorflow.keras.layers import Dense, Dropout, Input\n",
            "from tensorflow.keras.callbacks import EarlyStopping\n",
            "from tensorflow.keras.regularizers import l2\n",
            "from scipy.interpolate import interp1d"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Caricamento del dataset\n",
            "col_names = ['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', \n",
            "             'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist', 'class']\n\n",
            "df = pd.read_csv(\"magic04.data\", names=col_names)\n\n",
            "# Mappiamo le lettere in 0 (hadron) e 1 (gamma)\n",
            "df['class'] = df['class'].map({'h': 0, 'g': 1})\n\n",
            "print(\"Dataset caricato con successo in locale! Dimensioni:\", df.shape)"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["## Suddivisione del Dataset (Train, Val, Test)\n", "Per addestrare i nostri modelli in modo corretto dividiamo il dataset in tre parti: il 60% per il Training Set, il 20% per il Validation Set e il 20% per il Test Set."]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Separiamo features e target\n",
            "X = df.drop(['class'], axis=1)\n",
            "y = df['class']\n",
            "seed = 42\n\n",
            "# Primo split: 60% Train, 40% Temp\n",
            "X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=seed, stratify=y)\n\n",
            "# Secondo split: 50% di Temp -> 20% Val, 20% Test\n",
            "X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=seed, stratify=y_temp)\n\n",
            "df_train = pd.concat([X_train, y_train], axis=1)"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["# Analisi Esplorativa\n", "Controlliamo l'assenza di valori nulli o mancanti. Tracciamo poi istogrammi e boxplot per capire la distribuzione di ciascuna variabile e generiamo la matrice di correlazione per evidenziare relazioni lineari tra le features."]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Verifica dei valori NaN\n",
            "print(\"Valori mancanti per colonna:\\n\", df.isnull().sum())\n",
            "print(f\"\\nDuplicati trovati prima della pulizia: {df_train.duplicated().sum()}\")\n\n",
            "df_train = df_train.drop_duplicates()\n",
            "print(\"Dataset Training dopo rimozione duplicati:\", df_train.shape)"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Diagramma a torta della target\n",
            "signal_class = df_train['class'].value_counts()\n",
            "plt.figure(figsize=(6, 6))\n",
            "plt.pie(signal_class, labels=['gamma (1)', 'hadron (0)'], autopct='%1.1f%%', startangle=90, colors=['#ff9999','#66b3ff'])\n",
            "plt.title('Distribuzione del Target nel Training Set')\n",
            "plt.axis('equal')\n",
            "plt.show()"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Istogrammi\n",
            "numeric_cols = df_train.select_dtypes(include=['float64', 'int64']).columns\n",
            "numeric_cols = [c for c in numeric_cols if c != 'class']\n",
            "sns.set_style(\"whitegrid\")\n",
            "n_cols = 3\n",
            "n_rows = math.ceil(len(numeric_cols) / n_cols)\n",
            "plt.figure(figsize=(15, 4 * n_rows))\n\n",
            "for i, col in enumerate(numeric_cols):\n",
            "    plt.subplot(n_rows, n_cols, i + 1)\n",
            "    sns.histplot(df_train[col], kde=True, bins=30, edgecolor='black')\n",
            "    plt.title(f'Distribuzione di {col}')\n",
            "    plt.xlabel('')\n",
            "    plt.ylabel('Frequenza')\n\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Boxplot\n",
            "plt.figure(figsize=(15, 4 * n_rows))\n",
            "for i, col in enumerate(numeric_cols):\n",
            "    plt.subplot(n_rows, n_cols, i + 1)\n",
            "    sns.boxplot(x='class', y=col, hue='class', data=df_train, palette='Set2', legend=False)\n",
            "    plt.title(f'{col} vs Class')\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Matrice di Correlazione\n",
            "plt.figure(figsize=(10, 8))\n",
            "corr_matrix = df_train[numeric_cols].corr()\n",
            "sns.heatmap(corr_matrix, annot=True, fmt=\".2f\", cmap='coolwarm', linewidths=0.5)\n",
            "plt.title('Matrice di Correlazione')\n",
            "plt.show()"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["# Preprocessing e Scalatura\n", "Standardizziamo i dati in modo che abbiano media 0 e deviazione standard 1, il che aiuta notevolmente le reti neurali a convergere. Assicuriamo anche che i target siano di tipo intero."]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "scaler = StandardScaler()\n\n",
            "# Addestriamo lo scaler SOLO sul Train per evitare data leak\n",
            "X_train_scaled = scaler.fit_transform(X_train)\n",
            "X_val_scaled = scaler.transform(X_val)\n",
            "X_test_scaled = scaler.transform(X_test)\n\n",
            "y_train = y_train.astype(\"int64\")\n",
            "y_test = y_test.astype(\"int64\")\n",
            "y_val = y_val.astype(\"int64\")"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["# Introduzione del Rumore (Noise Injection)\n", "Per studiare la robustezza dei modelli, creeremo due tipi di rumore:\n", "- **Feature Noise:** Aggiunta di rumore gaussiano alle features.\n", "- **Label Noise:** Inversione casuale di una percentuale delle etichette (es. da 0 a 1 e viceversa)."]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "def add_gaussian_noise(X, noise_level=0.1, seed=42):\n",
            "    np.random.seed(seed)\n",
            "    noise = np.random.normal(loc=0.0, scale=noise_level, size=X.shape)\n",
            "    return X + noise\n\n",
            "def add_label_noise(y, noise_level=0.1, seed=42):\n",
            "    np.random.seed(seed)\n",
            "    y_noisy = np.array(y).copy()\n",
            "    n_samples = len(y_noisy)\n",
            "    n_flips = int(n_samples * noise_level)\n",
            "    flip_indices = np.random.choice(n_samples, size=n_flips, replace=False)\n",
            "    y_noisy[flip_indices] = 1 - y_noisy[flip_indices]\n",
            "    return y_noisy\n\n",
            "noise_levels = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["# Modelli Neurali\n", "Implementiamo due varianti di rete neurale:\n", "1. **Base:** Architettura semplice con due strati nascosti.\n", "2. **Pro (Regolarizzata):** Architettura più profonda che include Dropout, Regolarizzazione L2, Class Weight e Early Stopping per limitare l'overfitting quando i dati sono rumorosi."]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "def train_base_network(X_train_input, y_train_input, X_val_input, y_val_input, epochs=75, batch_size=32, verbose=0):\n",
            "    model = Sequential()\n",
            "    model.add(Input(shape=(X_train_input.shape[1],)))\n",
            "    model.add(Dense(32, activation='relu'))\n",
            "    model.add(Dense(16, activation='relu'))\n",
            "    model.add(Dense(1, activation='sigmoid'))\n\n",
            "    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)\n",
            "    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])\n\n",
            "    history = model.fit(X_train_input, y_train_input, epochs=epochs, batch_size=batch_size, \n",
            "                        validation_data=(X_val_input, y_val_input), verbose=verbose)\n\n",
            "    val_acc = history.history['val_accuracy'][-1]\n",
            "    return model, history\n\n",
            "def train_pro_network(X_train_input, y_train_input, X_val_input, y_val_input, epochs=150, batch_size=32, verbose=0, dropout_rate=0.2, l2_lambda=1e-4, patience=15):\n",
            "    model = Sequential()\n",
            "    model.add(Input(shape=(X_train_input.shape[1],)))\n",
            "    model.add(Dense(32, activation='relu', kernel_regularizer=l2(l2_lambda)))\n",
            "    model.add(Dropout(dropout_rate))\n",
            "    model.add(Dense(16, activation='relu', kernel_regularizer=l2(l2_lambda)))\n",
            "    model.add(Dropout(dropout_rate))\n",
            "    model.add(Dense(1, activation='sigmoid'))\n\n",
            "    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)\n",
            "    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])\n\n",
            "    classes = np.unique(y_train_input)\n",
            "    weights = compute_class_weight(class_weight='balanced', classes=classes, y=np.array(y_train_input))\n",
            "    class_weights_dict = {int(c): w for c, w in zip(classes, weights)}\n\n",
            "    early_stop = EarlyStopping(monitor='val_loss', patience=patience, restore_best_weights=True)\n\n",
            "    history = model.fit(X_train_input, y_train_input, epochs=epochs, batch_size=batch_size,\n",
            "                        validation_data=(X_val_input, y_val_input), class_weight=class_weights_dict,\n",
            "                        callbacks=[early_stop], verbose=verbose)\n\n",
            "    return model, history\n\n",
            "def evaluate_network(model, history, X_test_input, y_test_input, model_name=\"Modello\"):\n",
            "    print(f\"\\n\" + \"=\"*50)\n",
            "    print(f\" RISULTATI ESPERIMENTO: {model_name}\")\n",
            "    print(\"=\"*50)\n",
            "    score = model.evaluate(X_test_input, y_test_input, verbose=0)\n",
            "    print(f\"Test loss: {score[0]:.4f} - Test accuracy: {score[1]:.4f}\")\n\n",
            "    # Grafici di Accuracy e Loss\n",
            "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "    axes[0].plot(history.history['accuracy'], label='Train')\n",
            "    axes[0].plot(history.history['val_accuracy'], label='Validation')\n",
            "    axes[0].set_title(f'{model_name} - Accuracy')\n",
            "    axes[0].set_ylabel('Accuracy'); axes[0].set_xlabel('Epoch')\n",
            "    axes[0].legend(loc='lower right'); axes[0].grid(True)\n\n",
            "    axes[1].plot(history.history['loss'], label='Train')\n",
            "    axes[1].plot(history.history['val_loss'], label='Validation')\n",
            "    axes[1].set_title(f'{model_name} - Loss')\n",
            "    axes[1].set_ylabel('Loss'); axes[1].set_xlabel('Epoch')\n",
            "    axes[1].legend(loc='upper right'); axes[1].grid(True)\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n\n",
            "    y_pred_probs = model.predict(X_test_input, verbose=0)\n",
            "    y_pred_nn = (y_pred_probs > 0.5).astype(\"int64\")\n",
            "    \n",
            "    # Matrice di Confusione\n",
            "    cm = confusion_matrix(y_test_input, y_pred_nn)\n",
            "    plt.figure(figsize=(5,4))\n",
            "    sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\")\n",
            "    plt.xlabel(\"Predicted Label\"); plt.ylabel(\"True Label\")\n",
            "    plt.title(f\"Confusion Matrix - {model_name}\")\n",
            "    plt.show()\n\n",
            "    # Report finale\n",
            "    print(f\"Accuratezza Finale: {accuracy_score(y_test_input, y_pred_nn):.4f}\")\n",
            "    print(\"\\nReport di Classificazione:\")\n",
            "    print(classification_report(y_test_input, y_pred_nn, zero_division=0))\n",
            "    print(\"=\"*50 + \"\\n\")"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["## Addestramento Rete Neurale Base"]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# --- BASELINE (Dati Puliti) ---\n",
            "print(\">>> Addestramento NN Base Baseline (Dati Puliti)\")\n",
            "model_nn_clean, hist_nn_clean = train_base_network(X_train_scaled, y_train, X_val_scaled, y_val)\n",
            "evaluate_network(model_nn_clean, hist_nn_clean, X_test_scaled, y_test, model_name=\"NN Baseline\")\n\n",
            "modelli_nn_fn = {'Baseline': model_nn_clean}\n",
            "modelli_nn_ln = {'Baseline': model_nn_clean}\n",
            "modelli_nn_comb = {'Baseline': model_nn_clean}\n\n",
            "# Addestramento ai vari livelli di rumore\n",
            "for lvl in noise_levels:\n",
            "    print(f\"\\n--- Addestramento NN Base con RUMORE {int(lvl*100)}% ---\")\n\n",
            "    X_fn = add_gaussian_noise(X_train_scaled, noise_level=lvl)\n",
            "    model_fn, hist_fn = train_base_network(X_fn, y_train, X_val_scaled, y_val)\n",
            "    modelli_nn_fn[f'Rumore {int(lvl*100)}%'] = model_fn\n",
            "    evaluate_network(model_fn, hist_fn, X_test_scaled, y_test, model_name=f\"NN Base Feature Noise {int(lvl*100)}%\")\n\n",
            "    y_ln = add_label_noise(y_train, noise_level=lvl) \n",
            "    model_ln, hist_ln = train_base_network(X_train_scaled, y_ln, X_val_scaled, y_val)\n",
            "    modelli_nn_ln[f'Rumore {int(lvl*100)}%'] = model_ln\n",
            "    evaluate_network(model_ln, hist_ln, X_test_scaled, y_test, model_name=f\"NN Base Label Noise {int(lvl*100)}%\")\n\n",
            "    model_comb, hist_comb = train_base_network(X_fn, y_ln, X_val_scaled, y_val)\n",
            "    modelli_nn_comb[f'Rumore {int(lvl*100)}%'] = model_comb\n",
            "    evaluate_network(model_comb, hist_comb, X_test_scaled, y_test, model_name=f\"NN Base Combinato {int(lvl*100)}%\")"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["## Addestramento Rete Neurale PRO (Regolarizzata)"]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# --- BASELINE PRO (Dati Puliti) ---\n",
            "print(\">>> Addestramento NN Pro Baseline (Dati Puliti)\")\n",
            "model_nn_clean_pro, hist_nn_clean_pro = train_pro_network(X_train_scaled, y_train, X_val_scaled, y_val)\n",
            "evaluate_network(model_nn_clean_pro, hist_nn_clean_pro, X_test_scaled, y_test, model_name=\"NN Baseline PRO\")\n\n",
            "# Uso la baseline corretta per la rete PRO!\n",
            "modelli_nn_fn_pro = {'Baseline': model_nn_clean_pro}\n",
            "modelli_nn_ln_pro = {'Baseline': model_nn_clean_pro}\n",
            "modelli_nn_comb_pro = {'Baseline': model_nn_clean_pro}\n\n",
            "# Addestramento ai vari livelli di rumore per la versione PRO\n",
            "for lvl in noise_levels:\n",
            "    print(f\"\\n--- Addestramento NN PRO con RUMORE {int(lvl*100)}% ---\")\n\n",
            "    X_fn = add_gaussian_noise(X_train_scaled, noise_level=lvl)\n",
            "    model_fn_pro, hist_fn_pro = train_pro_network(X_fn, y_train, X_val_scaled, y_val)\n",
            "    modelli_nn_fn_pro[f'Rumore {int(lvl*100)}%'] = model_fn_pro\n",
            "    evaluate_network(model_fn_pro, hist_fn_pro, X_test_scaled, y_test, model_name=f\"NN Pro Feature Noise {int(lvl*100)}%\")\n\n",
            "    y_ln = add_label_noise(y_train, noise_level=lvl) \n",
            "    model_ln_pro, hist_ln_pro = train_pro_network(X_train_scaled, y_ln, X_val_scaled, y_val)\n",
            "    modelli_nn_ln_pro[f'Rumore {int(lvl*100)}%'] = model_ln_pro\n",
            "    evaluate_network(model_ln_pro, hist_ln_pro, X_test_scaled, y_test, model_name=f\"NN Pro Label Noise {int(lvl*100)}%\")\n\n",
            "    model_comb_pro, hist_comb_pro = train_pro_network(X_fn, y_ln, X_val_scaled, y_val)\n",
            "    modelli_nn_comb_pro[f'Rumore {int(lvl*100)}%'] = model_comb_pro\n",
            "    evaluate_network(model_comb_pro, hist_comb_pro, X_test_scaled, y_test, model_name=f\"NN Pro Combinato {int(lvl*100)}%\")"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["# Valutazione e Confronto\n", "Valutiamo i modelli usando Accuracy, F1 Macro, Recall Macro e AUC per capire come ciascuna tipologia di rumore ne degrada le performance. Infine stampiamo grafici che comparano direttamente la robustezza della rete base contro la rete PRO regolarizzata."]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "PALETTE = ['#1f77b4', '#d62728', '#2ca02c', '#9467bd', '#ff7f0e']\n\n",
            "def _nn_proba(model, X):\n",
            "    return np.asarray(model.predict(X, verbose=0)).ravel()\n\n",
            "def compute_metrics(model, X_test_input, y_test_input):\n",
            "    proba = _nn_proba(model, X_test_input)\n",
            "    y_pred = (proba > 0.5).astype(int)\n",
            "    return {\n",
            "        'accuracy':     accuracy_score(y_test_input, y_pred),\n",
            "        'recall_macro': recall_score(y_test_input, y_pred, average='macro', zero_division=0),\n",
            "        'f1_macro':     f1_score(y_test_input, y_pred, average='macro', zero_division=0),\n",
            "        'auc':          roc_auc_score(y_test_input, proba),\n",
            "    }\n\n",
            "def _level_from_name(name):\n",
            "    if 'baseline' in name.lower(): return 0\n",
            "    m = re.search(r'(\\d+)', name)\n",
            "    return int(m.group(1)) if m else np.nan\n\n",
            "def results_dataframe(models_dict, X_test_input, y_test_input, modello='NN base', tipo_rumore=''):\n",
            "    rows = []\n",
            "    for name, model in models_dict.items():\n",
            "        rows.append({'modello': modello, 'tipo_rumore': tipo_rumore,\n",
            "                     'livello': _level_from_name(name),\n",
            "                     **compute_metrics(model, X_test_input, y_test_input)})\n",
            "    return pd.DataFrame(rows).sort_values('livello').reset_index(drop=True)\n\n",
            "# Dataframe Modelli Base\n",
            "df_fn   = results_dataframe(modelli_nn_fn,   X_test_scaled, y_test, 'NN base', 'Feature noise')\n",
            "df_ln   = results_dataframe(modelli_nn_ln,   X_test_scaled, y_test, 'NN base', 'Label noise')\n",
            "df_comb = results_dataframe(modelli_nn_comb, X_test_scaled, y_test, 'NN base', 'Combinato')\n\n",
            "# Dataframe Modelli PRO\n",
            "df_fn_pro = results_dataframe(modelli_nn_fn_pro, X_test_scaled, y_test, 'NN pro', 'Feature noise')\n",
            "df_ln_pro = results_dataframe(modelli_nn_ln_pro, X_test_scaled, y_test, 'NN pro', 'Label noise')\n",
            "df_comb_pro = results_dataframe(modelli_nn_comb_pro, X_test_scaled, y_test, 'NN pro', 'Combinato')"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "def plot_metrics_grid(dfs, title='Impatto del rumore sulle metriche (NN base)'):\n",
            "    metriche = [('accuracy','Accuracy'), ('f1_macro','F1 (macro)'),\n",
            "                ('recall_macro','Recall (macro)'), ('auc','AUC')]\n",
            "    fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n",
            "    for ax, (key, nice) in zip(axes.ravel(), metriche):\n",
            "        for (label, df), color in zip(dfs.items(), PALETTE):\n",
            "            d = df.sort_values('livello')\n",
            "            ax.plot(d['livello'], d[key], marker='o', lw=2, markersize=6, color=color, label=label)\n",
            "        ax.set_title(nice, fontweight='bold'); ax.set_xlabel('Livello di rumore (%)')\n",
            "        ax.set_ylabel(nice); ax.grid(alpha=0.3)\n",
            "    axes.ravel()[0].legend(frameon=True)\n",
            "    fig.suptitle(title, fontsize=15, fontweight='bold')\n",
            "    plt.tight_layout(rect=[0, 0, 1, 0.97]); plt.show()\n\n",
            "def plot_degradation(dfs, metric='accuracy', title=None):\n",
            "    plt.figure(figsize=(9, 5.5))\n",
            "    for (label, df), color in zip(dfs.items(), PALETTE):\n",
            "        d = df.sort_values('livello')\n",
            "        plt.plot(d['livello'], d[metric], marker='o', lw=2.2, markersize=7, color=color, label=label)\n",
            "        plt.annotate(f\"{d[metric].iloc[-1]:.2f}\", (d['livello'].iloc[-1], d[metric].iloc[-1]),\n",
            "                     textcoords=\"offset points\", xytext=(6, 0), fontsize=9, color=color)\n",
            "    first = list(dfs.values())[0]\n",
            "    b = first[first['livello'] == 0][metric]\n",
            "    if len(b):\n",
            "        plt.axhline(float(b.iloc[0]), ls='--', color='grey', alpha=0.6, lw=1, label='Baseline (0%)')\n",
            "    plt.xlabel('Livello di rumore (%)'); plt.ylabel(metric.replace('_', ' ').upper())\n",
            "    plt.title(title or f'Degrado di {metric} al crescere del rumore', fontweight='bold')\n",
            "    plt.grid(alpha=0.3); plt.legend(frameon=True); plt.tight_layout(); plt.show()\n\n",
            "def plot_base_vs_pro(df_base, df_pro, metric='accuracy', tipo='Feature noise'):\n",
            "    m = df_base.merge(df_pro, on='livello', suffixes=('_base', '_pro')).sort_values('livello')\n",
            "    plt.figure(figsize=(9, 5.5))\n",
            "    plt.plot(m['livello'], m[metric+'_base'], marker='o', lw=2.2, color=PALETTE[0], label='NN base')\n",
            "    plt.plot(m['livello'], m[metric+'_pro'],  marker='s', lw=2.2, color=PALETTE[1], label='NN pro (regolarizzata)')\n",
            "    plt.fill_between(m['livello'], m[metric+'_base'], m[metric+'_pro'], alpha=0.12, color='grey')\n",
            "    plt.xlabel('Livello di rumore (%)'); plt.ylabel(metric.replace('_', ' ').upper())\n",
            "    plt.title(f'NN base vs NN pro — {tipo} ({metric})', fontweight='bold')\n",
            "    plt.grid(alpha=0.3); plt.legend(frameon=True); plt.tight_layout(); plt.show()"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# 1) Metriche aggregate per Rete Base\n",
            "dati_base = {'Feature noise': df_fn, 'Label noise': df_ln, 'Combinato': df_comb}\n",
            "plot_metrics_grid(dati_base, title='Impatto del rumore sulle metriche (NN Base)')\n\n",
            "# 2) Curve di degrado sull'Accuracy\n",
            "plot_degradation(dati_base, metric='accuracy', title=\"Impatto del rumore sull'accuracy (NN base)\")\n\n",
            "# 3) Confronti Diretti Base vs Pro!\n",
            "plot_base_vs_pro(df_fn, df_fn_pro, metric='accuracy', tipo='Feature noise')\n",
            "plot_base_vs_pro(df_ln, df_ln_pro, metric='accuracy', tipo='Label noise')\n",
            "plot_base_vs_pro(df_comb, df_comb_pro, metric='accuracy', tipo='Rumore Combinato')"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["## Confronto Curve ROC"]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "def plot_roc_comparison(models_dict, X_test_input, y_test_input, title_suffix=\"\"):\n",
            "    plt.figure(figsize=(10, 7))\n",
            "    colors = ['blue', 'green', 'orange', 'purple', 'brown']\n",
            "    for i, (name, model) in enumerate(models_dict.items()):\n",
            "        y_score = model.predict(X_test_input, verbose=0).ravel()\n",
            "        fpr, tpr, _ = roc_curve(y_test_input, y_score)\n",
            "        auc = roc_auc_score(y_test_input, y_score)\n",
            "        color = colors[i % len(colors)]\n",
            "        plt.plot(fpr, tpr, color=color, lw=2, label=f'{name} (AUC = {auc:.4f})')\n\n",
            "    plt.plot([0, 1], [0, 1], color='red', linestyle='--', lw=1, alpha=0.5)\n",
            "    plt.xlim([0.0, 1.0]); plt.ylim([0.0, 1.05])\n",
            "    plt.xlabel('False Positive Rate (1 - Specificità)')\n",
            "    plt.ylabel('True Positive Rate (Sensibilità)')\n",
            "    plt.title(f'Confronto Curva ROC: Impatto del Rumore {title_suffix}')\n",
            "    plt.legend(loc=\"lower right\")\n",
            "    plt.grid(alpha=0.3)\n",
            "    plt.show()"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Confronto ROC sui modelli con rumore sulle FEATURE\n",
            "reti_da_confrontare_fn = {\n",
            "    'Baseline (Dati Puliti)': modelli_nn_fn['Baseline'],\n",
            "    'Rumore 10%': modelli_nn_fn['Rumore 10%'],\n",
            "    'Rumore 30%': modelli_nn_fn['Rumore 30%'],\n",
            "    'Rumore 50%': modelli_nn_fn['Rumore 50%'],\n",
            "}\n",
            "plot_roc_comparison(reti_da_confrontare_fn, X_test_scaled, y_test, \"(Feature Noise)\")"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Confronto ROC sui modelli con rumore sulle ETICHETTE\n",
            "reti_da_confrontare_ln = {\n",
            "    'Baseline (Dati Puliti)': modelli_nn_ln['Baseline'],\n",
            "    'Rumore 10%': modelli_nn_ln['Rumore 10%'],\n",
            "    'Rumore 30%': modelli_nn_ln['Rumore 30%'],\n",
            "    'Rumore 50%': modelli_nn_ln['Rumore 50%'],\n",
            "}\n",
            "plot_roc_comparison(reti_da_confrontare_ln, X_test_scaled, y_test, \"(Label Noise)\")"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Confronto differenziale delle ROC tra NN base e NN pro\n",
            "score_base = model_nn_clean.predict(X_test_scaled, verbose=0).ravel()\n",
            "score_pro  = model_nn_clean_pro.predict(X_test_scaled, verbose=0).ravel()\n",
            "fpr_base, tpr_base, _ = roc_curve(y_test, score_base)\n",
            "fpr_pro,  tpr_pro,  _ = roc_curve(y_test, score_pro)\n\n",
            "# Griglia comune di FPR e interpolazione dei TPR sulla stessa scala\n",
            "fpr_grid = np.linspace(0, 1, 1000)\n",
            "tpr_base_grid = np.interp(fpr_grid, fpr_base, tpr_base)\n",
            "tpr_pro_grid  = np.interp(fpr_grid, fpr_pro,  tpr_pro)\n\n",
            "# Differenza (pro - base): se > 0 la rete pro e' sopra (migliore)\n",
            "diff = tpr_pro_grid - tpr_base_grid\n",
            "intersections = np.where(np.diff(np.sign(diff)))[0]\n\n",
            "print(\"--- ANALISI COMPARATIVA (NN pro vs NN base) ---\")\n",
            "for idx in intersections:\n",
            "    print(f\"Punto di intersezione rilevato a FPR ~ {fpr_grid[idx]:.3f}\")\n\n",
            "plt.figure(figsize=(10, 6))\n",
            "plt.plot(fpr_grid, diff, label='Differenza (pro - base)', color='purple')\n",
            "plt.axhline(0, color='black', linestyle='--')\n",
            "plt.fill_between(fpr_grid, 0, diff, where=(diff > 0), color='green', alpha=0.3, label='Dominanza NN pro')\n",
            "plt.fill_between(fpr_grid, 0, diff, where=(diff < 0), color='blue',  alpha=0.3, label='Dominanza NN base')\n",
            "plt.xlabel('False Positive Rate')\n",
            "plt.ylabel('Differenza TPR (Sensibilita)')\n",
            "plt.title('Differenziale di Performance: NN pro vs NN base')\n",
            "plt.legend(); plt.grid(True, alpha=0.3); plt.show()"
        ]},
        {"cell_type": "markdown", "metadata": {}, "source": ["# Modello Non Supervisionato (K-Means)\n", "Il K-Means tenta di trovare raggruppamenti (cluster) senza usare le etichette. Essendo un algoritmo basato solo sulle features, il **Label Noise** non ha alcun impatto su di esso, mentre il **Feature Noise** degraderà la qualità dei cluster formati."]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "def cluster_quality(X_scaled, y_true, k=2):\n",
            "    km = KMeans(n_clusters=k, n_init=10, random_state=seed)\n",
            "    labels = km.fit_predict(X_scaled)\n",
            "    y_true = np.array(y_true)\n",
            "    purity = sum(np.bincount(y_true[labels == c]).max() for c in np.unique(labels)) / len(y_true)\n",
            "    metrics = {\n",
            "        'ARI': adjusted_rand_score(y_true, labels),\n",
            "        'NMI': normalized_mutual_info_score(y_true, labels),\n",
            "        'purezza': purity,\n",
            "        'silhouette': silhouette_score(X_scaled, labels, sample_size=2000, random_state=seed),\n",
            "    }\n",
            "    return metrics, labels\n\n",
            "q_clean, labels_clean = cluster_quality(X_train_scaled, y_train, k=2)\n",
            "print(\"K-means (k=2) sui dati puliti:\")\n",
            "for m, v in q_clean.items():\n",
            "    print(f\"  {m:11s}: {v:.3f}\")"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "pc = PCA(n_components=2, random_state=seed).fit_transform(X_train_scaled)\n\n",
            "fig, ax = plt.subplots(1, 2, figsize=(14, 6))\n",
            "ax[0].scatter(pc[:, 0], pc[:, 1], c=labels_clean, cmap='coolwarm', s=6, alpha=0.4)\n",
            "ax[0].set_title('Cluster trovati da K-means (k=2)')\n",
            "ax[1].scatter(pc[:, 0], pc[:, 1], c=np.array(y_train), cmap='coolwarm', s=6, alpha=0.4)\n",
            "ax[1].set_title('Classi reali (gamma / hadron)')\n",
            "for a in ax:\n",
            "    a.set_xlabel('PC1'); a.set_ylabel('PC2')\n",
            "plt.tight_layout(); plt.show()"
        ]},
        {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
            "# Impatto del Feature Noise vs Label Noise su K-Means\n",
            "feature_levels = [0.0, 0.25, 0.5, 1.0, 1.5, 2.0]\n",
            "print(\"--- Effetto del Feature Noise su K-Means ---\")\n",
            "for lvl in feature_levels:\n",
            "    X_noisy = add_gaussian_noise(X_train_scaled, noise_level=lvl)\n",
            "    q, _ = cluster_quality(X_noisy, y_train, k=2)\n",
            "    print(f\"feature sigma={lvl:<4} | ARI={q['ARI']:.3f}  silhouette={q['silhouette']:.3f}  purezza={q['purezza']:.3f}\")\n\n",
            "y_train_flip = add_label_noise(y_train, noise_level=0.40)\n",
            "_, labels_lab = cluster_quality(X_train_scaled, y_train_flip, k=2)\n",
            "ari_part = adjusted_rand_score(labels_clean, labels_lab)\n",
            "print(\"\\n--- Effetto del Label Noise su K-Means (40%) ---\")\n",
            "print(f\"ARI tra clustering pulito e clustering con label noise: {ari_part:.3f} (= 1.0: partizione identica)\")\n",
            "print(\"Come previsto, K-means usa solo le feature: invertire le etichette non sposta i cluster.\")"
        ]}
    ]

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.5"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

    with open('/Users/matiasbonoli/Downloads/architettura/progettoArchiBonni.ipynb', 'w') as f:
        json.dump(notebook, f, indent=1)

    print("Notebook JSON scritto con successo!")

if __name__ == "__main__":
    create_notebook()
